image: google/dart

stages:
    - build
    - test
    - release

# set PUB_CACHE=.pub-cache env var
build:
    stage: build
    cache:
        key: pub-cache
        paths:
            - .dart_tool
            - .packages
            - .pub-cache
            - pubspec.lock
            - pubspec.yaml
            - build
        policy: push
    script:
        - pub get
        - pub run build_runner build
        - pub run webdev build

test:
    stage: test
    cache:
        key: pub-cache
        paths:
            - .dart_tool
            - .packages
            - .pub-cache
            - pubspec.lock
            - pubspec.yaml
            - build
        policy: pull
    script:
        - pub run test

release:
    stage: release
    only:
        - master
    image: docker:stable
    cache:
        key: pub-cache
        paths:
            - .dart_tool
            - .packages
            - .pub-cache
            - pubspec.lock
            - pubspec.yaml
            - build
        policy: pull
    script:
        - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
        - docker build -t mgkeiji/kvalour .
        - docker push mgkeiji/kvalour