image: google/dart:2.3.2-dev.0.1

stages:
    - build
    - test

# set PUB_CACHE=.pub-cache env var
build:
    stage: build
    cache:
        key: pub-cache
        paths:
            - .dart_tool
            - .packages
            - .pub-cache
            - pubspec.lock
            - pubspec.yaml
            - build
        policy: push
    script:
        - pub get
        - pub run webdev build
